### ISSUE TITLE
Code is sometimes run twice on app start, sometimes there is a crash

### ISSUE THREAD

**Issue by leaf-node** [AhsanSarwar45/flutter_boot_receiver#10]
Sometimes when starting the app in debug mode, I see the following messages. Similar to [an old firebase issue](https://stackoverflow.com/questions/74430484/firebase-background-message-handler-in-flutter-spawns-duplicate-isolate-and-runs), I'm seeing a doubling of threads in the call stack in VS Codium:

```
I/FlutterBootReceiverPlugin(16753): onAttachedToEngine
I/FlutterBackgroundExecutor(16753): Starting BootHandlerService...
I/FlutterBootReceiverPlugin(16753): onAttachedToEngine
Connecting to VM Service at ws://127.0.0.1:39249/1kDvHmBMVCk=/ws
Connected to the VM Service.
I/BootHandlerService(16753): BootHandlerService started!
I/FlutterBackgroundExecutor(16753): Executing Dart callback: -7767485495945997519...
W/BootHandlerService(16753): Attempted to start a duplicate background isolate. Returning...
```

![Screenshot From 2024-11-13 15-55-27](https://github.com/user-attachments/assets/5476ac09-4244-466e-a820-c61c645a344e)

I'm not sure that this is the right way to call this library, so I may experiment with this a bit.

```dart
/*
 * SPDX-FileCopyrightText: 2024 Open Alert Viewer authors
 *
 * SPDX-License-Identifier: MIT
 */

import 'dart:async';
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_boot_receiver/flutter_boot_receiver.dart';
import 'package:yaml/yaml.dart';

import 'app.dart';
import 'app/data_source/database.dart';
import 'background/background.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  if (Platform.isAndroid) {
    await BootReceiver.initialize(startApp);
  }
  await startApp();
}

@pragma('vm:entry-point')
Future<void> startApp() async {
  WidgetsFlutterBinding.ensureInitialized();
  var db = LocalDatabase();
  await db.migrate(showPath: true);
  var bgWorker = BackgroundWorker();
  String appVersion = await getVersion();
  await bgWorker.spawn(appVersion: appVersion);
  runApp(OAVapp(appVersion: appVersion, db: db, bgWorker: bgWorker));
}
```

Another time, I saw the following error message after stopping and trying to restart the app in debug mode:

```
Launching lib/main.dart on sdk gphone64 x86 64 in debug mode...
✓ Built build/app/outputs/flutter-apk/app-debug.apk
I/FlutterBootReceiverPlugin(17265): onAttachedToEngine
I/FlutterBackgroundExecutor(17265): Starting BootHandlerService...
I/FlutterBootReceiverPlugin(17265): onAttachedToEngine
Connecting to VM Service at ws://127.0.0.1:46697/N80325QdPXg=/ws
Connected to the VM Service.
W/BootHandlerService(17265): Attempted to start a duplicate background isolate. Returning...
[log] App data directory: /data/user/0/studio.okcode.open_alert_viewer/files/
I/BootHandlerService(17265): BootHandlerService started!
I/FlutterBackgroundExecutor(17265): Executing Dart callback: -7767485495945997519...
[log] App data directory: /data/user/0/studio.okcode.open_alert_viewer/files/
D/AndroidRuntime(17265): Shutting down VM
E/AndroidRuntime(17265): FATAL EXCEPTION: main
E/AndroidRuntime(17265): Process: studio.okcode.open_alert_viewer, PID: 17265
E/AndroidRuntime(17265): android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{d0fedbe u0 studio.okcode.open_alert_viewer/com.dexterous.flutterlocalnotifications.ForegroundService c:studio.okcode.open_alert_viewer}
E/AndroidRuntime(17265): 	at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2271)
E/AndroidRuntime(17265): 	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2239)
E/AndroidRuntime(17265): 	at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
E/AndroidRuntime(17265): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2557)
E/AndroidRuntime(17265): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(17265): 	at android.os.Looper.loopOnce(Looper.java:232)
E/AndroidRuntime(17265): 	at android.os.Looper.loop(Looper.java:317)
E/AndroidRuntime(17265): 	at android.app.ActivityThread.main(ActivityThread.java:8705)
E/AndroidRuntime(17265): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(17265): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
E/AndroidRuntime(17265): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
I/Process (17265): Sending signal. PID: 17265 SIG: 9
Lost connection to device.

Exited.
```

It all happened quickly, but there was a doubling of isolates. One of the background isolates started fine, but another looked like it was changing its isolate names in the call stack view before the process crashed.

**Comment by leaf-node** [comment]
Perhaps this is coming up due to the workaround I'm using in my code for issue #4.

**Comment by leaf-node** [comment]
The extra threads on Android 15 may be caused by this issue: <https://issuetracker.google.com/issues/381281310>

**Comment by leaf-node** [comment]
To see how I'm working around the SDK 35 bug (without your module), see: <https://stackoverflow.com/a/79246441/582326>. Maybe your module could implement something similar?
